Development
FreeCodeCamp-SLC/utahjs-gatsby pull request #11
Opened 2020-10-02 01:31 UTC by jgbowser

Built out a mobile first view of the hero section and hero content. Added some basic responsive styling expecting it to likely be adjusted as we settle on a final hero image. Let me know if you see any issues.

2020-10-07 00:32 UTC, briancbarrow commented on src/components/HeroBox.js
> +        <div className={heroBoxStyles.hero_subtext}>
This should be a `p` tag just so it's semantic.

2020-10-07 00:38 UTC, briancbarrow requested changes
Update `div`s to `p`s. Also rename the svg file

2020-10-07 01:05 UTC, briancbarrow approved these changes

2020-10-21 00:21 UTC, mikelnorth requested changes

2020-10-21 00:21 UTC, mikelnorth commented on gatsby/src/components/Hero.js
> +import heroStyles from '../styles/hero.module.css'
Lets move this styled components

2020-10-21 00:21 UTC, mikelnorth commented on gatsby/src/components/HeroBox.js
> +import heroBoxStyles from '../styles/hero-box.module.css';
same as above

2020-10-21 00:21 UTC, mikelnorth commented on gatsby/src/components/layout.css
> +@import url('https://fonts.googleapis.com/css2?family=Fira+Sans&family=Sanchez&display=swap');
Delete this file

2020-10-21 00:21 UTC, mikelnorth commented on gatsby/src/styles/hero-box.module.css
> +.hero_box {
Move to styled component

2020-10-21 01:00 UTC, mikelnorth commented on gatsby/src/components/HeroBox.js
> +      <a className="btn green" href="https://slack.utahjs.com">
import Button from 'react-bootstrap/button'

<Button href=''>Conferene</Button>

2020-10-21 16:12 UTC, mikelnorth approved these changes

2020-10-21 16:12 UTC, merged